A = float(input('Insira valor A: '))
B = float(input('Insira valor B: '))
C = float(input('Insira valor C: '))
print(f'Triângulo = {A*C/2:.3f}')
print(f'Circulo = {3.14159*C**2:.3f}')
print(f'Trapézio = {(A+B)*C/2:.3f}')
print(f'Quadrado = {B*B:.3f}')
print(f'Retângulo  = {A*B:.3f}')
print()